export const initialData = {
  wellMaster: {},
  resetWellMaster: {
    parent_well_id: null,
    well_drilling_parameter: {
      file_id: null,
      filename: null,
    },
    well_documents: [
      {
        file_id: null,
        filename: null,
        document_type: null,
        remark: null,
      },
    ],
    well_trajectory: {
      unit_type: null,
      physical_item_id: null,
      survey_start_date: null,
      survey_end_date: null,
      top_depth: null,
      base_depth: null,
      survey_type: null,
    },
    well_logs: [
      {
        unit_type: null,
        top_depth: null,
        base_depth: null,
        logs: null,
        physical_item_id: null,
      },
    ],
    well_cores: [
      {
        unit_type: null,
        top_depth: null,
        base_depth: null,
        core_diameter: null,
        core_type: null,
        core_show_type: null,
        remark: null,
        physical_item_id: null,
      },
    ],
    well_tests: [
      {
        test_type: null,
        run_num: null,
        test_num: null,
        base_depth: null,
        base_depth_ouom: null,
        bhp_z: null,
        bottom_choke_desc: null,
        bsw_percent: null,
        caliper_hole_diameter: null,
        caliper_hole_diameter_ouom: null,
        casing_pressure: null,
        casing_pressure_ouom: null,
        choke_size_desc: null,
        condensate_amount_percent: null,
        condensate_flow_amount: null,
        condensate_flow_amount_ouom: null,
        condensate_flow_amount_uom: null,
        condensate_gravity: null,
        condensate_ratio: null,
        condensate_ratio_ouom: null,
        damage_quality: null,
        flow_pressure: null,
        flow_pressure_ouom: null,
        flow_temperature: null,
        flow_temperature_ouom: null,
        gas_flow_amount: null,
        gas_flow_amount_ouom: null,
        gas_flow_amount_uom: null,
        gas_gravity: null,
        gor: null,
        gor_ouom: null,
        h2s_percent: null,
        hole_condition: null,
        max_condens_flow_rate: null,
        max_condens_flow_rate_ouom: null,
        max_gas_flow_rate: null,
        max_gas_flow_rate_ouom: null,
        max_hydrostatic_pressure: null,
        max_hydrostatic_press_ouom: null,
        max_oil_flow_rate: null,
        max_oil_flow_rate_ouom: null,
        max_water_flow_rate: null,
        max_water_flow_rate_ouom: null,
        oil_amount_percent: null,
        oil_flow_amount: null,
        oil_flow_amount_ouom: null,
        oil_flow_amount_uom: null,
        oil_gravity: null,
        permeability_quality: null,
        primary_fluid_recovered: null,
        production_method: null,
        rat_hole_diameter: null,
        rat_hole_diameter_ouom: null,
        rat_hole_length: null,
        rat_hole_length_ouom: null,
        remark: null,
        report_temperature: null,
        report_temperature_ouom: null,
        report_test_num: null,
        show_type: null,
        si_flow_ratio: null,
        start_time: null,
        start_timezone: null,
        static_pressure: null,
        static_pressure_ouom: null,
        strat_age: null,
        string_source: null,
        sulphur_ind: null,
        td: null,
        td_ouom: null,
        temperature_correction: null,
        temperature_correction_ind: null,
        temperature_correction_ouom: null,
        test_date: null,
        test_duration: null,
        test_duration_ouom: null,
        test_hole_diameter: null,
        test_hole_diameter_ouom: null,
        test_result_code: null,
        test_subtype: null,
        tool_open_time: null,
        tool_open_timezone: null,
        top_choke_desc: null,
        top_depth: null,
        top_depth_ouom: null,
        water_amount_percent: null,
        water_cut_percent: null,
        water_flow_amount: null,
        water_flow_amount_ouom: null,
        water_flow_amount_uom: null,
        wellbore_completion_type: null,
        z_factor: null,
      },
    ],
    seismic_line: {
      physical_item_id: null,
      seismic_line_name: null,
      average_velocity: null,
      shot_point_number: null,
      max_latitude: null,
      max_longitude: null,
      min_latitude: null,
      min_longitude: null,
      remark: null,
    },
    well_casings: [
      {
        top_depth: null,
        top_depth_ouom: null,
        base_depth: null,
        base_depth_ouom: null,
        hole_size: null,
        hole_size_ouom: null,
        inside_diameter: null,
        inside_diameter_ouom: null,
        outside_diameter: null,
        outside_diameter_ouom: null,
        cement_type: null,
        cement_amount: null,
        cement_amount_uom: null,
        remark: null,
      },
    ],
    well_equipments: [
      {
        purchase_date: null,
        commission_date: null,
        decommission_date: null,
        equipment_group: null,
        equipment_name: null,
        equipment_type: null,
        serial_num: null,
        description: null,
        remark: null,
      },
    ],
    well_completion: [
      {
        completion_obs_no: null,
        base_depth: null,
        base_depth_ouom: null,
        completion_date: null,
        completion_method: null,
        completion_type: null,
        remark: null,
        top_depth: null,
        top_depth_ouom: null,
      },
    ],
    well_ppfg: {
      file_id: null,
      filename: null,
    },
    well_schematic: {
      file_id: null,
      filename: null,
    },
    well_stratigraphy: [
      {
        unit_type: null,
        depth_datum: null,
        top_depth: null,
        bottom_depth: null,
        formation_name: null,
        lithology: null,
      },
    ],
    well_pressure: [
      {
        base_depth: null,
        base_depth_ouom: null,
        flow_casing_pressure: null,
        flow_casing_pressure_ouom: null,
        flow_tubing_pressure: null,
        flow_tubing_pressure_ouom: null,
        init_reservoir_pressure: null,
        init_reservoir_press_ouom: null,
        pool_datum: null,
        pool_datum_depth: null,
        pool_datum_depth_ouom: null,
        pr_str_form_obs_no: null,
        remark: null,
        shutin_casing_pressure: null,
        suhtin_casing_pressure_ouom: null,
        shutin_tubing_pressure: null,
        shutin_tubing_pressure_ouom: null,
        top_depth: null,
        top_depth_ouom: null,
        well_datum_depth: null,
        well_datum_ouom: null,
      },
    ],
    unit_type: null,
    well_level_type: null,
    well_class: null,
    well_profile_type: null,
    environment_type: null,
    surface_longitude: null,
    surface_latitude: null,
    bottom_hole_longitude: null,
    bottom_hole_latitude: null,
    spud_date: null,
    final_drill_date: null,
    completion_date: null,
    abandonment_date: null,
    rig_on_site_date: null,
    rig_release_date: null,
    maximum_inclination: null,
    azimuth: null,
    hydrocarbon_target: null,
    kick_off_point: null,
    difference_lat_msl: null,
    subsea_elev_ref_type: null,
    elev_ref_datum: null,
    rotary_table_elev: null,
    kb_elev: null,
    derrick_floor_elev: null,
    ground_elev: null,
    ground_elev_type: null,
    base_depth: null,
    water_depth: null,
    water_depth_datum: null,
    deepest_depth: null,
    depth_datum: null,
    depth_datum_elev: null,
    drill_td: null,
    top_depth: null,
    maximum_tvd: null,
    final_md: null,
    plugback_depth: null,
    whipstock_depth: null,
    water_acoustic_vel: null,
    net_pay: null,
    well_name: null,
    well_num: null,
    area_id: null,
    field_id: null,
    well_status: null,
    remark: null,
  },
  jobPlanExpDev: {
    job_plan: {
      well: {},
    },
  },
  jobPlanWoWs: {
    area_id: null,
    field_id: null,
    contract_type: null,
    afe_number: null,
    wpb_year: null,
    job_plan: {
      wrm_internal_kkks: null,
      wrm_pengadaan_equipment: null,
      wrm_pengadaan_services: null,
      wrm_pengadaan_handak: null,
      wrm_pengadaan_octg: null,
      wrm_pengadaan_lli: null,
      wrm_pengadaan_artificial_lift: null,
      wrm_sumur_berproduksi: null,
      wrm_fasilitas_produksi: null,
      wrm_persiapan_lokasi: null,
      wrm_well_integrity: null,
      start_date: null,
      end_date: null,
      total_budget: null,
      job_operation_days: [
        {
          unit_type: null,
          phase: null,
          depth_datum: null,
          depth_in: null,
          depth_out: null,
          operation_days: null,
        },
      ],
      job_hazards: [
        {
          hazard_type: null,
          hazard_description: null,
          severity: null,
          mitigation: null,
          remark: null,
        },
      ],
      job_documents: [
        {
          file_id: null,
          filename: null,
          document_type: null,
          remark: null,
        },
      ],
      job_project_management_team: [
        {
          company: null,
          position: null,
          name: null,
        },
      ],
      job_equipments: [
        {
          equipment: null,
          vendor: null,
        },
      ],
      job_hse_aspect: {
        near_miss: null,
        fatality: null,
        spill: null,
        unsafe_condition: null,
        unsafe_action: null,
        man_hour: null,
      },
      work_breakdown_structure: {
        events: [
          {
            event: null,
            start_date: null,
            end_date: null,
            remarks: null,
          },
        ],
        wrm_internal_kkks: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_equipment: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_services: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_handak: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_octg: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_lli: {
          start_date: null,
          end_date: null,
        },
        wrm_pengadaan_artificial_lift: {
          start_date: null,
          end_date: null,
        },
        wrm_sumur_berproduksi: {
          start_date: null,
          end_date: null,
        },
        wrm_fasilitas_produksi: {
          start_date: null,
          end_date: null,
        },
        wrm_persiapan_lokasi: {
          start_date: null,
          end_date: null,
        },
        wrm_well_integrity: {
          start_date: null,
          end_date: null,
        },
      },
      equipment: null,
      equipment_specifications: null,
      well_id: null,
      job_category: null,
      job_description: null,
      onstream_oil: null,
      onstream_gas: null,
      onstream_water_cut: null,
      target_oil: null,
      target_gas: null,
      target_water_cut: null,
      well_schematic: {
        file_id: null,
        filename: null,
      },
    },
  },
  wrmValues: {},
  jobOperationData: {
    report_date: null,
    avg_wob: null,
    avg_rop: null,
    avg_rpm: null,
    torque: null,
    stand_pipe_pressure: null,
    flow_rate: null,
    string_weight: null,
    rotating_weight: null,
    total_drilling_time: null,
    circulating_pressure: null,
    daily_cost: null,
    daily_mud_cost: null,
    day_supervisor: null,
    night_supervisor: null,
    engineer: null,
    geologist: null,
    day_summary: null,
    day_forecast: null,
    last_size: null,
    set_md: null,
    next_size: null,
    next_set_md: null,
    last_lot_emw: null,
    tol: null,
    start_mud_volume: null,
    lost_surface_mud_volume: null,
    lost_dh_mud_volume: null,
    dumped_mud_volume: null,
    built_mud_volume: null,
    ending_mud_volume: null,
    max_gas: null,
    conn_gas: null,
    trip_gas: null,
    back_gas: null,
    annular_velocity: null,
    pb: null,
    sys_hhp: null,
    hhpb: null,
    hsi: null,
    percent_psib: null,
    jet_velocity: null,
    impact_force: null,
    if_area: null,
    stop_cards: null,
    lta: null,
    spill: null,
    h2s_test: null,
    hse_mtg: null,
    kicktrip: null,
    kickdrill: null,
    fire: null,
    job_id: null,
    personnel: [
      {
        company: null,
        people: null,
      },
    ],
    Incidents: [
      {
        incidents_time: null,
        incident: null,
        incident_type: null,
        comments: null,
      },
    ],
    time_breakdowns: [
      {
        start_time: null,
        end_time: null,
        start_measured_depth: null,
        end_measured_depth: null,
        category: null,
        p: null,
        npt: null,
        code: null,
        operation: null,
      },
    ],
    bit_records: {
      bit_size: null,
      bit_number: null,
      bit_run: null,
      manufacturer: null,
      iadc_code: null,
      jets: null,
      serial: null,
      depth_out: null,
      depth_in: null,
      meterage: null,
      bit_hours: null,
      nozzels: null,
      dull_grade: null,
    },
    bottom_hole_assemblies: [
      {
        bha_number: null,
        bha_run: null,
        components: [],
      },
      {
        bha_number: null,
        bha_run: null,
        components: [],
      },
    ],
    drilling_fluids: [],
    mud_additives: [],
    bulk_materials: [],
    directional_surveys: [],
    pumps: [],
    weather: {
      temperature_high: null,
      temperature_low: null,
      chill_factor: null,
      wind_speed: null,
      wind_direction: null,
      barometric_pressure: null,
      wave_height: null,
      wave_current_speed: null,
      road_condition: null,
      visibility: null,
    },
  },
  initialOperationData: {
    bottom_hole_assembly: null,
  },
  updatedOperationData: {},
  FormOperationData: {},
  dataUser: {
    name: null,
    area: {
      id: null,
      label: null,
      name: null,
      phase: null,
      type: null,
      position: null,
      production_status: null,
      region: null,
    },
  },
};
