const ouomOptions = [
  { name: "ft", value: "ft" },
  { name: "m", value: "m" },
];

const diameterOptions = [
  { name: "mm", value: "mm" },
  { name: "inch", value: "inch" },
];

const amountOptions = [
  { name: "m3", value: "m3" },
  { name: "ft3", value: "ft3" },
  { name: "kg", value: "kg" },
  { name: "lbs", value: "lbs" },
];

const uomOptions = [
    { name: "ft", value: "ft" }, { name: "frac", value: "frac" }
  ]

export const WellTestsHeader = [
  { key: "test_type", headerName: "Test Type", type: "string", required: true },
  { key: "run_num", headerName: "Run Number", type: "string" },
  { key: "test_num", headerName: "Test Number", type: "string" },
  { key: "active_ind", headerName: "Active Indicator", type: "string" },
  { key: "base_depth", headerName: "Base Depth", type: "number" },
  {
    key: "base_depth_ouom",
    headerName: "Base Depth Ouom",
    type: "select",
    select: uomOptions,
  },
  {
    key: "base_strat_unit_id",
    headerName: "Base Strat Unit ID",
    type: "string",
  },
  { key: "bhp_z", headerName: "BHP Z", type: "number" },
  {
    key: "bottom_choke_desc",
    headerName: "Bottom Choke Description",
    type: "string",
  },
  { key: "bsw_percent", headerName: "BSW Percent", type: "number" },
  {
    key: "caliper_hole_diameter",
    headerName: "Caliper Hole Diameter",
    type: "number",
  },
  {
    key: "caliper_hole_diameter_ouom",
    headerName: "Caliper Hole Diameter Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "cased_hole_ind", headerName: "Cased Hole Indicator", type: "string" },
  { key: "casing_pressure", headerName: "Casing Pressure", type: "number" },
  {
    key: "casing_pressure_ouom",
    headerName: "Casing Pressure Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "choke_size_desc",
    headerName: "Choke Size Description",
    type: "string",
  },
  {
    key: "completion_obs_no",
    headerName: "Completion Observation Number",
    type: "string",
  },
  { key: "completion_source", headerName: "Completion Source", type: "string" },
  {
    key: "condensate_amount_percent",
    headerName: "Condensate Amount Percent",
    type: "number",
  },
  {
    key: "condensate_flow_amount",
    headerName: "Condensate Flow Amount",
    type: "number",
  },
  {
    key: "condensate_flow_amount_ouom",
    headerName: "Condensate Flow Amount Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "condensate_flow_amount_uom",
    headerName: "Condensate Flow Amount UOM",
    type: "select",
    select: uomOptions,
  },
  {
    key: "condensate_gravity",
    headerName: "Condensate Gravity",
    type: "number",
  },
  { key: "condensate_ratio", headerName: "Condensate Ratio", type: "number" },
  {
    key: "condensate_ratio_ouom",
    headerName: "Condensate Ratio Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "damage_quality", headerName: "Damage Quality", type: "string" },
  { key: "effective_date", headerName: "Effective Date", type: "date" },
  {
    key: "event_obs_no",
    headerName: "Event Observation Number",
    type: "select",
    select: uomOptions,
  },
  { key: "event_source", headerName: "Event Source", type: "string" },
  { key: "expiry_date", headerName: "Expiry Date", type: "date" },
  { key: "flow_pressure", headerName: "Flow Pressure", type: "number" },
  {
    key: "flow_pressure_ouom",
    headerName: "Flow Pressure Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "flow_temperature", headerName: "Flow Temperature", type: "number" },
  {
    key: "flow_temperature_ouom",
    headerName: "Flow Temperature Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "gas_flow_amount", headerName: "Gas Flow Amount", type: "number" },
  {
    key: "gas_flow_amount_ouom",
    headerName: "Gas Flow Amount Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "gas_flow_amount_uom",
    headerName: "Gas Flow Amount UOM",
    type: "select",
    select: uomOptions,
  },
  { key: "gas_gravity", headerName: "Gas Gravity", type: "number" },
  { key: "gor", headerName: "GOR", type: "number" },
  {
    key: "gor_ouom",
    headerName: "GOR Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "h2s_percent", headerName: "H2S Percent", type: "number" },
  { key: "hole_condition", headerName: "Hole Condition", type: "string" },
  {
    key: "max_condens_flow_rate",
    headerName: "Max Condensate Flow Rate",
    type: "number",
  },
  {
    key: "max_condens_flow_rate_ouom",
    headerName: "Max Condensate Flow Rate Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "max_gas_flow_rate", headerName: "Max Gas Flow Rate", type: "number" },
  {
    key: "max_gas_flow_rate_ouom",
    headerName: "Max Gas Flow Rate Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "max_hydrostatic_pressure",
    headerName: "Max Hydrostatic Pressure",
    type: "number",
  },
  {
    key: "max_hydrostatic_press_ouom",
    headerName: "Max Hydrostatic Pressure Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "max_oil_flow_rate", headerName: "Max Oil Flow Rate", type: "number" },
  {
    key: "max_oil_flow_rate_ouom",
    headerName: "Max Oil Flow Rate Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "max_water_flow_rate",
    headerName: "Max Water Flow Rate",
    type: "number",
  },
  {
    key: "max_water_flow_rate_ouom",
    headerName: "Max Water Flow Rate Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "oil_amount_percent",
    headerName: "Oil Amount Percent",
    type: "number",
  },
  { key: "oil_flow_amount", headerName: "Oil Flow Amount", type: "number" },
  {
    key: "oil_flow_amount_ouom",
    headerName: "Oil Flow Amount Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "oil_flow_amount_uom",
    headerName: "Oil Flow Amount UOM",
    type: "select",
    select: uomOptions,
  },
  { key: "oil_gravity", headerName: "Oil Gravity", type: "number" },
  {
    key: "permeability_quality",
    headerName: "Permeability Quality",
    type: "string",
  },
  { key: "ppdm_guid", headerName: "PPDM GUID", type: "string" },
  {
    key: "primary_fluid_recovered",
    headerName: "Primary Fluid Recovered",
    type: "string",
  },
  { key: "production_method", headerName: "Production Method", type: "string" },
  { key: "prod_string_id", headerName: "Production String ID", type: "string" },
  {
    key: "prod_str_form_obs_no",
    headerName: "Production String Form Observation Number",
    type: "string",
  },
  { key: "rat_hole_diameter", headerName: "Rat Hole Diameter", type: "number" },
  {
    key: "rat_hole_diameter_ouom",
    headerName: "Rat Hole Diameter Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "rat_hole_length", headerName: "Rat Hole Length", type: "number" },
  {
    key: "rat_hole_length_ouom",
    headerName: "Rat Hole Length Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "remark", headerName: "Remark", type: "string" },
  {
    key: "reported_strat_unit_id",
    headerName: "Reported Strat Unit ID",
    type: "string",
  },
  {
    key: "report_temperature",
    headerName: "Report Temperature",
    type: "number",
  },
  {
    key: "report_temperature_ouom",
    headerName: "Report Temperature Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "report_test_num", headerName: "Report Test Number", type: "string" },
  { key: "show_type", headerName: "Show Type", type: "string" },
  { key: "si_flow_ratio", headerName: "SI Flow Ratio", type: "number" },
  { key: "start_time", headerName: "Start Time", type: "date" },
  { key: "start_timezone", headerName: "Start Timezone", type: "string" },
  { key: "static_pressure", headerName: "Static Pressure", type: "number" },
  {
    key: "static_pressure_ouom",
    headerName: "Static Pressure Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "strat_age", headerName: "Strat Age", type: "string" },
  {
    key: "strat_age_name_set_id",
    headerName: "Strat Age Name Set ID",
    type: "string",
  },
  { key: "strat_name_set_id", headerName: "Strat Name Set ID", type: "string" },
  { key: "string_source", headerName: "String Source", type: "string" },
  { key: "sulphur_ind", headerName: "Sulphur Indicator", type: "string" },
  { key: "td", headerName: "TD", type: "number" },
  { key: "td_ouom", headerName: "TD Unit", type: "select", select: uomOptions },
  {
    key: "temperature_correction",
    headerName: "Temperature Correction",
    type: "number",
  },
  {
    key: "temperature_correction_ind",
    headerName: "Temperature Correction Indicator",
    type: "string",
  },
  {
    key: "temperature_correction_ouom",
    headerName: "Temperature Correction Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "test_company", headerName: "Test Company", type: "string" },
  { key: "test_date", headerName: "Test Date", type: "date" },
  { key: "test_duration", headerName: "Test Duration", type: "number" },
  {
    key: "test_duration_ouom",
    headerName: "Test Duration Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "test_hole_diameter",
    headerName: "Test Hole Diameter",
    type: "number",
  },
  {
    key: "test_hole_diameter_ouom",
    headerName: "Test Hole Diameter Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "test_result_code", headerName: "Test Result Code", type: "string" },
  { key: "test_subtype", headerName: "Test Subtype", type: "string" },
  { key: "tool_open_time", headerName: "Tool Open Time", type: "date" },
  {
    key: "tool_open_timezone",
    headerName: "Tool Open Timezone",
    type: "string",
  },
  {
    key: "top_choke_desc",
    headerName: "Top Choke Description",
    type: "string",
  },
  { key: "top_depth", headerName: "Top Depth", type: "number" },
  {
    key: "top_depth_ouom",
    headerName: "Top Depth Unit",
    type: "select",
    select: uomOptions,
  },
  { key: "top_strat_unit_id", headerName: "Top Strat Unit ID", type: "string" },
  {
    key: "water_amount_percent",
    headerName: "Water Amount Percent",
    type: "number",
  },
  { key: "water_cut_percent", headerName: "Water Cut Percent", type: "number" },
  { key: "water_flow_amount", headerName: "Water Flow Amount", type: "number" },
  {
    key: "water_flow_amount_ouom",
    headerName: "Water Flow Amount Unit",
    type: "select",
    select: uomOptions,
  },
  {
    key: "water_flow_amount_uom",
    headerName: "Water Flow Amount UOM",
    type: "select",
    select: uomOptions,
  },
  {
    key: "wellbore_completion_type",
    headerName: "Wellbore Completion Type",
    type: "string",
  },
  { key: "z_factor", headerName: "Z Factor", type: "number" },
  { key: "row_changed_by", headerName: "Row Changed By", type: "string" },
  { key: "row_changed_date", headerName: "Row Changed Date", type: "date" },
  { key: "row_created_by", headerName: "Row Created By", type: "string" },
  { key: "row_created_date", headerName: "Row Created Date", type: "date" },
  { key: "row_effective_date", headerName: "Row Effective Date", type: "date" },
  { key: "row_expiry_date", headerName: "Row Expiry Date", type: "date" },
  { key: "row_quality", headerName: "Row Quality", type: "string" },
];

export const WellCasingHeader = [
  { key: "top_depth", headerName: "Top Depth", type: "number" },
  {
    key: "top_depth_ouom",
    headerName: "Top Depth Unit",
    type: "select",
    select: ouomOptions,
  },
  { key: "base_depth", headerName: "Base Depth", type: "number" },
  {
    key: "base_depth_ouom",
    headerName: "Base Depth Unit",
    type: "select",
    select: ouomOptions,
  },
  { key: "hole_size", headerName: "Hole Size", type: "number" },
  {
    key: "hole_size_ouom",
    headerName: "Hole Size Unit",
    type: "select",
    select: ouomOptions,
  },
  { key: "inside_diameter", headerName: "Inside Diameter", type: "number" },
  {
    key: "inside_diameter_ouom",
    headerName: "Inside Diameter Unit",
    type: "select",
    select: diameterOptions,
  },
  { key: "outside_diameter", headerName: "Outside Diameter", type: "number" },
  {
    key: "outside_diameter_ouom",
    headerName: "Outside Diameter Unit",
    type: "select",
    select: diameterOptions,
  },
  { key: "cement_type", headerName: "Cement Type", type: "string" },
  { key: "cement_amount", headerName: "Cement Amount", type: "number" },
  {
    key: "cement_amount_uom",
    headerName: "Cement Amount Unit",
    type: "select",
    select: amountOptions,
  },
  { key: "remark", headerName: "Remark", type: "string" },
  { key: "asdasd", headerName: "asdasd", type: "dateOnly" },
];

export const WellEquipmentHeader = [
  {
    key: "purchase_date",
    headerName: "Purchase Date",
    type: "dateOnly",
    required: true,
  },
  {
    key: "commission_date",
    headerName: "Commission Date",
    type: "dateOnly",
    required: true,
  },
  {
    key: "decommission_date",
    headerName: "Decommission Date",
    type: "dateOnly",
  },
  {
    key: "equipment_group",
    headerName: "Equipment Group",
    type: "string",
    required: true,
  },
  {
    key: "equipment_name",
    headerName: "Equipment Name",
    type: "string",
    required: true,
  },
  {
    key: "equipment_type",
    headerName: "Equipment Type",
    type: "string",
    required: true,
  },
  {
    key: "serial_num",
    headerName: "Serial Number",
    type: "string",
    required: true,
  },
  {
    key: "description",
    headerName: "Description",
    type: "string",
  },
  {
    key: "remark",
    headerName: "Remark",
    type: "string",
  },
];

export const WellCompletionHeader = [
  {
    key: "completion_obs_no",
    headerName: "Completion Observation No",
    type: "number",
    required: true,
  },
  {
    key: "base_depth",
    headerName: "Base Depth",
    type: "number",
    required: true,
  },
  {
    key: "base_depth_ouom",
    headerName: "Base Depth OUOM",
    type: "select",
    required: true,
    select: [
      { value: "m", name: "Meters" },
      { value: "ft", name: "Feet" },
      { value: "in", name: "Inches" },
    ],
  },
  {
    key: "completion_date",
    headerName: "Completion Date",
    type: "dateOnly",
    required: true,
  },
  {
    key: "completion_method",
    headerName: "Completion Method",
    type: "string",
    required: true,
    select: [
      { value: "hydraulic_fracturing", name: "Hydraulic Fracturing" },
      { value: "conventional", name: "Conventional" },
      { value: "horizontal_drilling", name: "Horizontal Drilling" },
    ],
  },
  {
    key: "completion_type",
    headerName: "Completion Type",
    type: "string",
    required: true,
    select: [
      { value: "open_hole", name: "Open Hole" },
      { value: "cased_hole", name: "Cased Hole" },
      { value: "liner", name: "Liner" },
    ],
  },
  {
    key: "remark",
    headerName: "Remark",
    type: "string",
  },
  {
    key: "top_depth",
    headerName: "Top Depth",
    type: "number",
    required: true,
  },
  {
    key: "top_depth_ouom",
    headerName: "Top Depth OUOM",
    type: "select",
    required: true,
    select: [
      { value: "m", name: "Meters" },
      { value: "ft", name: "Feet" },
      { value: "in", name: "Inches" },
    ],
  },
];

export const WellPressureHeader =[
    {
      key: "base_depth",
      headerName: "Base Depth",
      type: "number",
      required: false
    },
    {
      key: "base_depth_ouom",
      headerName: "Base Depth OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "flow_casing_pressure",
      headerName: "Flow Casing Pressure",
      type: "number",
      required: false
    },
    {
      key: "flow_casing_pressure_ouom",
      headerName: "Flow Casing Pressure OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "flow_tubing_pressure",
      headerName: "Flow Tubing Pressure",
      type: "number",
      required: false
    },
    {
      key: "flow_tubing_pressure_ouom",
      headerName: "Flow Tubing Pressure OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "init_reservoir_pressure",
      headerName: "Initial Reservoir Pressure",
      type: "number",
      required: false
    },
    {
      key: "init_reservoir_press_ouom",
      headerName: "Initial Reservoir Pressure OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "pool_datum",
      headerName: "Pool Datum",
      type: "string",
      required: false
    },
    {
      key: "pool_datum_depth",
      headerName: "Pool Datum Depth",
      type: "number",
      required: false
    },
    {
      key: "pool_datum_depth_ouom",
      headerName: "Pool Datum Depth OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "pr_str_form_obs_no",
      headerName: "Pressure String Form Observation No",
      type: "number",
      required: false
    },
    {
      key: "remark",
      headerName: "Remark",
      type: "string",
      required: false
    },
    {
      key: "shutin_casing_pressure",
      headerName: "Shut-in Casing Pressure",
      type: "number",
      required: false
    },
    {
      key: "suhtin_casing_pressure_ouom",
      headerName: "Shut-in Casing Pressure OUOM",
      type: "select",
      select: ouomOptions,
      required: false
    },
    {
      key: "shutin_tubing_pressure",
      headerName: "Shut-in Tubing Pressure",
      type: "number",
      required: false
    },
    {
      key: "shutin_tubing_pressure_ouom",
      headerName: "Shut-in Tubing Pressure OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "top_depth",
      headerName: "Top Depth",
      type: "number",
      required: false
    },
    {
      key: "top_depth_ouom",
      headerName: "Top Depth OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    },
    {
      key: "well_datum_depth",
      headerName: "Well Datum Depth",
      type: "number",
      required: false
    },
    {
      key: "well_datum_ouom",
      headerName: "Well Datum OUOM",
      type: "select",
      required: false,
      select: ouomOptions
    }
  ];

  export const WellTestsHeaderMaster = [
    { key: "test_type", headerName: "Test Type", type: "string", required: true },
    { key: "run_num", headerName: "Run Number", type: "string" },
    { key: "test_num", headerName: "Test Number", type: "string" },
    // { key: "active_ind", headerName: "Active Indicator", type: "string" },
    { key: "base_depth", headerName: "Base Depth", type: "number" },
    {
      key: "base_depth_ouom",
      headerName: "Base Depth Ouom",
      type: "select",
      select: uomOptions,
    },
    // {
    //   key: "base_strat_unit_id",
    //   headerName: "Base Strat Unit ID",
    //   type: "string",
    // },
    { key: "bhp_z", headerName: "BHP Z", type: "number" },
    {
      key: "bottom_choke_desc",
      headerName: "Bottom Choke Description",
      type: "string",
    },
    { key: "bsw_percent", headerName: "BSW Percent", type: "number" },
    {
      key: "caliper_hole_diameter",
      headerName: "Caliper Hole Diameter",
      type: "number",
    },
    {
      key: "caliper_hole_diameter_ouom",
      headerName: "Caliper Hole Diameter Unit",
      type: "select",
      select: uomOptions,
    },
    // { key: "cased_hole_ind", headerName: "Cased Hole Indicator", type: "string" },
    { key: "casing_pressure", headerName: "Casing Pressure", type: "number" },
    {
      key: "casing_pressure_ouom",
      headerName: "Casing Pressure Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "choke_size_desc",
      headerName: "Choke Size Description",
      type: "string",
    },
    // {
    //   key: "completion_obs_no",
    //   headerName: "Completion Observation Number",
    //   type: "string",
    // },
    // { key: "completion_source", headerName: "Completion Source", type: "string" },
    {
      key: "condensate_amount_percent",
      headerName: "Condensate Amount Percent",
      type: "number",
    },
    {
      key: "condensate_flow_amount",
      headerName: "Condensate Flow Amount",
      type: "number",
    },
    {
      key: "condensate_flow_amount_ouom",
      headerName: "Condensate Flow Amount Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "condensate_flow_amount_uom",
      headerName: "Condensate Flow Amount UOM",
      type: "select",
      select: uomOptions,
    },
    {
      key: "condensate_gravity",
      headerName: "Condensate Gravity",
      type: "number",
    },
    { key: "condensate_ratio", headerName: "Condensate Ratio", type: "number" },
    {
      key: "condensate_ratio_ouom",
      headerName: "Condensate Ratio Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "damage_quality", headerName: "Damage Quality", type: "string" },
    // { key: "effective_date", headerName: "Effective Date", type: "date" },
    // {
    //   key: "event_obs_no",
    //   headerName: "Event Observation Number",
    //   type: "select",
    //   select: uomOptions,
    // },
    // { key: "event_source", headerName: "Event Source", type: "string" },
    // { key: "expiry_date", headerName: "Expiry Date", type: "date" },
    { key: "flow_pressure", headerName: "Flow Pressure", type: "number" },
    {
      key: "flow_pressure_ouom",
      headerName: "Flow Pressure Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "flow_temperature", headerName: "Flow Temperature", type: "number" },
    {
      key: "flow_temperature_ouom",
      headerName: "Flow Temperature Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "gas_flow_amount", headerName: "Gas Flow Amount", type: "number" },
    {
      key: "gas_flow_amount_ouom",
      headerName: "Gas Flow Amount Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "gas_flow_amount_uom",
      headerName: "Gas Flow Amount UOM",
      type: "select",
      select: uomOptions,
    },
    { key: "gas_gravity", headerName: "Gas Gravity", type: "number" },
    { key: "gor", headerName: "GOR", type: "number" },
    {
      key: "gor_ouom",
      headerName: "GOR Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "h2s_percent", headerName: "H2S Percent", type: "number" },
    { key: "hole_condition", headerName: "Hole Condition", type: "string" },
    {
      key: "max_condens_flow_rate",
      headerName: "Max Condensate Flow Rate",
      type: "number",
    },
    {
      key: "max_condens_flow_rate_ouom",
      headerName: "Max Condensate Flow Rate Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "max_gas_flow_rate", headerName: "Max Gas Flow Rate", type: "number" },
    {
      key: "max_gas_flow_rate_ouom",
      headerName: "Max Gas Flow Rate Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "max_hydrostatic_pressure",
      headerName: "Max Hydrostatic Pressure",
      type: "number",
    },
    {
      key: "max_hydrostatic_press_ouom",
      headerName: "Max Hydrostatic Pressure Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "max_oil_flow_rate", headerName: "Max Oil Flow Rate", type: "number" },
    {
      key: "max_oil_flow_rate_ouom",
      headerName: "Max Oil Flow Rate Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "max_water_flow_rate",
      headerName: "Max Water Flow Rate",
      type: "number",
    },
    {
      key: "max_water_flow_rate_ouom",
      headerName: "Max Water Flow Rate Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "oil_amount_percent",
      headerName: "Oil Amount Percent",
      type: "number",
    },
    { key: "oil_flow_amount", headerName: "Oil Flow Amount", type: "number" },
    {
      key: "oil_flow_amount_ouom",
      headerName: "Oil Flow Amount Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "oil_flow_amount_uom",
      headerName: "Oil Flow Amount UOM",
      type: "select",
      select: uomOptions,
    },
    { key: "oil_gravity", headerName: "Oil Gravity", type: "number" },
    {
      key: "permeability_quality",
      headerName: "Permeability Quality",
      type: "string",
    },
    // { key: "ppdm_guid", headerName: "PPDM GUID", type: "string" },
    {
      key: "primary_fluid_recovered",
      headerName: "Primary Fluid Recovered",
      type: "string",
    },
    { key: "production_method", headerName: "Production Method", type: "string" },
    // { key: "prod_string_id", headerName: "Production String ID", type: "string" },
    // {
    //   key: "prod_str_form_obs_no",
    //   headerName: "Production String Form Observation Number",
    //   type: "string",
    // },
    { key: "rat_hole_diameter", headerName: "Rat Hole Diameter", type: "number" },
    {
      key: "rat_hole_diameter_ouom",
      headerName: "Rat Hole Diameter Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "rat_hole_length", headerName: "Rat Hole Length", type: "number" },
    {
      key: "rat_hole_length_ouom",
      headerName: "Rat Hole Length Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "remark", headerName: "Remark", type: "string" },
    // {
    //   key: "reported_strat_unit_id",
    //   headerName: "Reported Strat Unit ID",
    //   type: "string",
    // },
    {
      key: "report_temperature",
      headerName: "Report Temperature",
      type: "number",
    },
    {
      key: "report_temperature_ouom",
      headerName: "Report Temperature Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "report_test_num", headerName: "Report Test Number", type: "string" },
    { key: "show_type", headerName: "Show Type", type: "string" },
    { key: "si_flow_ratio", headerName: "SI Flow Ratio", type: "number" },
    { key: "start_time", headerName: "Start Time", type: "date" },
    { key: "start_timezone", headerName: "Start Timezone", type: "string" },
    { key: "static_pressure", headerName: "Static Pressure", type: "number" },
    {
      key: "static_pressure_ouom",
      headerName: "Static Pressure Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "strat_age", headerName: "Strat Age", type: "string" },
    // {
    //   key: "strat_age_name_set_id",
    //   headerName: "Strat Age Name Set ID",
    //   type: "string",
    // },
    // { key: "strat_name_set_id", headerName: "Strat Name Set ID", type: "string" },
    { key: "string_source", headerName: "String Source", type: "string" },
    { key: "sulphur_ind", headerName: "Sulphur Indicator", type: "string" },
    { key: "td", headerName: "TD", type: "number" },
    { key: "td_ouom", headerName: "TD Unit", type: "select", select: uomOptions },
    {
      key: "temperature_correction",
      headerName: "Temperature Correction",
      type: "number",
    },
    {
      key: "temperature_correction_ind",
      headerName: "Temperature Correction Indicator",
      type: "string",
    },
    {
      key: "temperature_correction_ouom",
      headerName: "Temperature Correction Unit",
      type: "select",
      select: uomOptions,
    },
    // { key: "test_company", headerName: "Test Company", type: "string" },
    { key: "test_date", headerName: "Test Date", type: "date" },
    { key: "test_duration", headerName: "Test Duration", type: "number" },
    {
      key: "test_duration_ouom",
      headerName: "Test Duration Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "test_hole_diameter",
      headerName: "Test Hole Diameter",
      type: "number",
    },
    {
      key: "test_hole_diameter_ouom",
      headerName: "Test Hole Diameter Unit",
      type: "select",
      select: uomOptions,
    },
    { key: "test_result_code", headerName: "Test Result Code", type: "string" },
    { key: "test_subtype", headerName: "Test Subtype", type: "string" },
    { key: "tool_open_time", headerName: "Tool Open Time", type: "date" },
    {
      key: "tool_open_timezone",
      headerName: "Tool Open Timezone",
      type: "string",
    },
    {
      key: "top_choke_desc",
      headerName: "Top Choke Description",
      type: "string",
    },
    { key: "top_depth", headerName: "Top Depth", type: "number" },
    {
      key: "top_depth_ouom",
      headerName: "Top Depth Unit",
      type: "select",
      select: uomOptions,
    },
    // { key: "top_strat_unit_id", headerName: "Top Strat Unit ID", type: "string" },
    {
      key: "water_amount_percent",
      headerName: "Water Amount Percent",
      type: "number",
    },
    { key: "water_cut_percent", headerName: "Water Cut Percent", type: "number" },
    { key: "water_flow_amount", headerName: "Water Flow Amount", type: "number" },
    {
      key: "water_flow_amount_ouom",
      headerName: "Water Flow Amount Unit",
      type: "select",
      select: uomOptions,
    },
    {
      key: "water_flow_amount_uom",
      headerName: "Water Flow Amount UOM",
      type: "select",
      select: uomOptions,
    },
    {
      key: "wellbore_completion_type",
      headerName: "Wellbore Completion Type",
      type: "string",
    },
    { key: "z_factor", headerName: "Z Factor", type: "number" },
    // { key: "row_changed_by", headerName: "Row Changed By", type: "string" },
    // { key: "row_changed_date", headerName: "Row Changed Date", type: "date" },
    // { key: "row_created_by", headerName: "Row Created By", type: "string" },
    // { key: "row_created_date", headerName: "Row Created Date", type: "date" },
    // { key: "row_effective_date", headerName: "Row Effective Date", type: "date" },
    // { key: "row_expiry_date", headerName: "Row Expiry Date", type: "date" },
    // { key: "row_quality", headerName: "Row Quality", type: "string" },
  ];