export const ValidateFormJobPlanning = (values) => {
  const errors = {};
  const formData = {
    job_plan: {
      well: {
        well_type: null,
        well_profile_type: null,
        well_directional_type: null,
        environment_type: null,
        maximum_inclination: null,
        azimuth: null,
        depth_datum: null,
        kick_off_point: null,
        uwi: null,
        well_name: null,
        alias_long_name: null,
        surface_longitude: null,
        surface_latitude: null,
        bottom_hole_longitude: null,
        bottom_hole_latitude: null,
        rotary_table_elev: null,
        kb_elev: null,
        derrick_floor_elev: null,
        ground_elev: null,
        mean_sea_level: null,
        final_md: null,
        maximum_tvd: null,
        spud_date: null,
        final_drill_date: null,
        completion_date: null,
        well_stratigraphy: null,
        file_id: null,
        filename: null,
        unit_type: null,
        well_ppfg: null,
        well_materials: null,
        well_schematic: null,
        well_log_plan: null,
        well_drilling_parameter_plan: null,
        well_core_plan: null,
        well_test_plan: null,
      },
      start_date: null,
      end_date: null,
      rig_type: null,
      rig_horse_power: null,
      rig_name: null,
      total_budget: null,
      wrm_pembebasan_lahan: false,
      wrm_ippkh: false,
      wrm_ukl_upl: false,
      wrm_amdal: false,
      wrm_pengadaan_rig: false,
      wrm_pengadaan_drilling_services: false,
      wrm_pengadaan_lli: false,
      wrm_persiapan_lokasi: false,
      wrm_internal_kkks: false,
      wrm_evaluasi_subsurface: false,
      work_breakdown_structure: {
        events: [],
      },
      job_operation_days: [],
      job_hazards: [],
      job_project_management_team: [],
      job_equipment: [],
      job_hse_aspect: {
        near_miss: null,
        fatality: null,
        spill: null,
        unsafe_condition: null,
        unsafe_action: null,
        man_hour: null,
      },
      seismic_line: {
        file_id: null,
        seismic_line_name: null,
        shot_point_number: null,
      },
    },
    area_id: null,
    field_id: null,
    contract_type: null,
    afe_number: null,
    wpb_year: null,
  };
};
